/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    projects: Project;
    'project-categories': ProjectCategory;
    services: Service;
    testimonials: Testimonial;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'project-categories': ProjectCategoriesSelect<false> | ProjectCategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Konta administratorów panelu CMS
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Biblioteka zdjęć - przesyłaj zdjęcia realizacji, usług i inne
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Opis zdjęcia dla osób niewidomych i SEO
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Podstrony serwisu (O nas, itp.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * np. "o-nas" → strona będzie pod adresem /o-nas
   */
  slug: string;
  /**
   * Nagłówek widoczny na górze strony
   */
  hero?: {
    heading?: string | null;
    subheading?: string | null;
    image?: (string | null) | Media;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ustawienia widoczności w Google
   */
  meta?: {
    /**
     * Tytuł wyświetlany w wynikach Google
     */
    title?: string | null;
    /**
     * Krótki opis wyświetlany w wynikach Google
     */
    description?: string | null;
    /**
     * Wyświetlany przy udostępnianiu linku na FB/Messenger
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Wyróżnione realizacje pojawiają się na stronie głównej. Wszystkie widoczne na /realizacje
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  /**
   * np. "kuchnia-nowoczesna" → /realizacje/kuchnia-nowoczesna
   */
  slug: string;
  category: string | ProjectCategory;
  /**
   * Pokaż na stronie głównej
   */
  featured?: boolean | null;
  /**
   * Widoczny na karcie realizacji i na górze podstrony
   */
  description: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Wyświetlane na karcie realizacji i jako hero
   */
  mainImage: string | Media;
  /**
   * Dodatkowe zdjęcia realizacji
   */
  gallery?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Informacje wyświetlane w bocznym panelu realizacji
   */
  details?: {
    client?: string | null;
    location?: string | null;
    year?: string | null;
    scope?: string | null;
    materials?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  /**
   * Mniejsza liczba = wyżej na liście
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kategorie do grupowania realizacji (np. Kuchnie, Szafy, Łazienki)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories".
 */
export interface ProjectCategory {
  id: string;
  name: string;
  /**
   * np. "kuchnie" - używany w adresie URL
   */
  slug: string;
  description?: string | null;
  /**
   * Mniejsza liczba = wyżej na liście
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Karty usług widoczne na stronie głównej (sekcja "Usługi") i na podstronie /uslugi
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  /**
   * np. "kuchnie-na-wymiar" → /uslugi/kuchnie-na-wymiar
   */
  slug: string;
  /**
   * Wyświetlany na karcie usługi na stronie głównej
   */
  shortDescription: string;
  /**
   * Szczegółowy opis na podstronie usługi
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Nazwa ikony Lucide (np. "ruler", "hammer", "paintbrush")
   */
  icon?: string | null;
  image?: (string | null) | Media;
  /**
   * Lista zalet wyświetlana przy usłudze
   */
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Mniejsza liczba = wyżej na liście
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Wyróżnione opinie pojawiają się w sliderze na stronie głównej (sekcja "Opinie")
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  author: string;
  /**
   * np. "Właściciel domu, Pajęczno"
   */
  role?: string | null;
  content: string;
  /**
   * Ocena od 1 do 5 gwiazdek
   */
  rating?: number | null;
  /**
   * Opcjonalnie - która realizacja dotyczy tej opinii
   */
  project?: (string | null) | Project;
  /**
   * Pokaż na stronie głównej
   */
  featured?: boolean | null;
  /**
   * Mniejsza liczba = wyżej na liście
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Wiadomości wysłane przez formularz kontaktowy na stronie
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  /**
   * Zaznacz po przeczytaniu wiadomości
   */
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'project-categories';
        value: string | ProjectCategory;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
        image?: T;
      };
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  featured?: T;
  description?: T;
  content?: T;
  mainImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  details?:
    | T
    | {
        client?: T;
        location?: T;
        year?: T;
        scope?: T;
        materials?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories_select".
 */
export interface ProjectCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  content?: T;
  icon?: T;
  image?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  role?: T;
  content?: T;
  rating?: T;
  project?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Widoczne w lewym górnym rogu na każdej stronie. Zmienia się na białe przy scrollowaniu
   */
  logo?: (string | null) | Media;
  /**
   * Linki widoczne w górnym pasku na każdej stronie + w menu mobilnym
   */
  navItems?:
    | {
        /**
         * Tekst wyświetlany w menu, np. "O nas", "Realizacje"
         */
        label: string;
        /**
         * Adres docelowy, np. "/o-nas", "/realizacje", "#kontakt"
         */
        link: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Wyróżniony przycisk po prawej stronie menu na każdej stronie
   */
  ctaButton?: {
    /**
     * np. "Bezpłatna wycena"
     */
    label?: string | null;
    /**
     * np. "/kontakt"
     */
    link?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Logo widoczne w stopce na dole każdej strony
   */
  logo?: (string | null) | Media;
  /**
   * Tekst pod logo w stopce na dole każdej strony
   */
  description?: string | null;
  /**
   * Kolumny linków w środkowej części stopki (np. "Usługi", "Firma")
   */
  columns?:
    | {
        /**
         * Nagłówek nad linkami w stopce, np. "Usługi", "Firma"
         */
        title: string;
        links?:
          | {
              label: string;
              link: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Adres, telefon i email widoczne w prawej części stopki na dole każdej strony
   */
  contactInfo?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  /**
   * Ikony social media widoczne w stopce na dole każdej strony
   */
  socialLinks?:
    | {
        platform?: ('facebook' | 'instagram' | 'pinterest' | 'linkedin' | 'youtube') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tekst na samym dole strony, np. "© 2026 Kalabi. Wszelkie prawa zastrzeżone."
   */
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  /**
   * Ogólny opis firmy - używany w metadanych i udostępnianiu
   */
  siteDescription?: string | null;
  /**
   * Pełny adres, np. https://kalabi.pl - potrzebny do linków i SEO
   */
  siteUrl: string;
  /**
   * Główne logo firmy - używane jako domyślne w nagłówku i stopce
   */
  logo?: (string | null) | Media;
  /**
   * Mała ikona widoczna na karcie przeglądarki obok nazwy strony
   */
  favicon?: (string | null) | Media;
  companyInfo?: {
    /**
     * Oficjalna nazwa firmy
     */
    name?: string | null;
    nip?: string | null;
    /**
     * Wyświetlany na stronie /kontakt i w stopce
     */
    address?: string | null;
    /**
     * Wyświetlany w pasku nad menu, w stopce i na stronie /kontakt. Kliknięcie uruchamia połączenie
     */
    phone?: string | null;
    /**
     * Wyświetlany w pasku nad menu, w stopce i na stronie /kontakt. Kliknięcie otwiera program pocztowy
     */
    email?: string | null;
    /**
     * Link "Otwórz w Mapach Google" pod mapą na stronie /kontakt
     */
    googleMapsUrl?: string | null;
    /**
     * Ikony wyświetlane w pasku nad menu, w stopce i w menu mobilnym
     */
    socialLinks?:
      | {
          platform: 'facebook' | 'instagram' | 'youtube' | 'pinterest' | 'linkedin';
          /**
           * Pełny link, np. https://www.facebook.com/...
           */
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Wyświetlany przy udostępnianiu linku do strony na Facebook/Messenger/WhatsApp
   */
  ogImage?: (string | null) | Media;
  seo?: {
    /**
     * Wyświetlany w karcie przeglądarki i w wynikach Google gdy podstrona nie ma własnego tytułu
     */
    defaultTitle?: string | null;
    /**
     * %s zostanie zastąpione tytułem podstrony, np. "O nas | Kalabi"
     */
    titleTemplate?: string | null;
    /**
     * Opis pod tytułem w wynikach Google gdy podstrona nie ma własnego opisu
     */
    defaultDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero: {
    /**
     * Duży, biały tekst na środku banera na górze strony głównej
     */
    heading: string;
    /**
     * Mniejszy tekst pod nagłówkiem na banerze
     */
    subheading?: string | null;
    /**
     * Zdjęcia przewijające się w tle banera na górze strony głównej. Dodaj 2-3 zdjęcia dla efektu slideshow
     */
    slides?:
      | {
          image: string | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Złoty przycisk na banerze, np. "Bezpłatna wycena"
     */
    ctaText?: string | null;
    /**
     * Dokąd prowadzi złoty przycisk, np. "/kontakt"
     */
    ctaLink?: string | null;
    /**
     * Przezroczysty przycisk obok głównego na banerze, np. "Zobacz realizacje"
     */
    secondaryCtaText?: string | null;
    /**
     * Dokąd prowadzi drugi przycisk, np. "/realizacje"
     */
    secondaryCtaLink?: string | null;
  };
  videoSection?: {
    /**
     * Mały złoty tekst nad nagłówkiem sekcji filmów na stronie głównej, np. "Nasze realizacje"
     */
    label?: string | null;
    /**
     * Nagłówek sekcji filmów na stronie głównej
     */
    heading?: string | null;
    /**
     * Filmy wyświetlane w karuzeli na stronie głównej. Pierwszy film odtwarza się automatycznie.
     */
    videos?:
      | {
          /**
           * Wyświetlany pod filmem, np. "Kuchnia nowoczesna w bieli"
           */
          title: string;
          /**
           * Wklej link z YouTube lub Vimeo, np. https://www.youtube.com/watch?v=ABC123 lub https://vimeo.com/123456
           */
          url: string;
          /**
           * Własna miniaturka filmu. Jeśli puste, użyty zostanie kadr z YouTube/Vimeo.
           */
          thumbnail?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  servicesSection?: {
    /**
     * Mały złoty tekst nad nagłówkiem, np. "Nasze usługi"
     */
    label?: string | null;
    /**
     * Nagłówek sekcji usług na stronie głównej
     */
    heading?: string | null;
    /**
     * Tekst pod nagłówkiem sekcji usług na stronie głównej
     */
    description?: string | null;
  };
  projectsSection?: {
    /**
     * Mały złoty tekst nad nagłówkiem, np. "Nasze realizacje"
     */
    label?: string | null;
    /**
     * Nagłówek sekcji realizacji na stronie głównej
     */
    heading?: string | null;
    /**
     * Tekst pod nagłówkiem sekcji realizacji na stronie głównej
     */
    description?: string | null;
    /**
     * Przycisk pod realizacjami na stronie głównej, np. "Zobacz wszystkie realizacje"
     */
    ctaText?: string | null;
    /**
     * np. "/realizacje"
     */
    ctaLink?: string | null;
  };
  ctaBanner?: {
    /**
     * Duży biały tekst na banerze CTA, np. "Masz pomysł na meble? Porozmawiajmy!"
     */
    heading?: string | null;
    /**
     * Tekst pod nagłówkiem na banerze CTA
     */
    description?: string | null;
    /**
     * Zdjęcie w tle ciemnego banera CTA na stronie głównej
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Przycisk na banerze CTA, np. "Skontaktuj się"
     */
    ctaText?: string | null;
    /**
     * np. "/kontakt"
     */
    ctaLink?: string | null;
  };
  testimonialsSection?: {
    /**
     * Mały złoty tekst nad nagłówkiem, np. "Opinie klientów"
     */
    label?: string | null;
    /**
     * Nagłówek sekcji opinii na stronie głównej
     */
    heading?: string | null;
    /**
     * Tekst pod nagłówkiem sekcji opinii na stronie głównej
     */
    description?: string | null;
  };
  meta?: {
    /**
     * Tytuł strony głównej w wynikach Google i na karcie przeglądarki
     */
    title?: string | null;
    /**
     * Opis pod tytułem w wynikach Google dla strony głównej
     */
    description?: string | null;
    /**
     * Wyświetlany przy udostępnianiu linku do strony głównej na Facebook/Messenger
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  hero?: {
    /**
     * Duży biały tekst na ciemnym banerze na górze strony /o-nas
     */
    heading?: string | null;
    /**
     * Tekst pod nagłówkiem na banerze strony /o-nas
     */
    subheading?: string | null;
    /**
     * Zdjęcie w tle ciemnego banera na górze strony /o-nas
     */
    image?: (string | null) | Media;
  };
  intro?: {
    /**
     * Mały złoty tekst nad nagłówkiem, np. "Nasza historia"
     */
    label?: string | null;
    /**
     * Nagłówek sekcji o firmie na stronie /o-nas
     */
    heading?: string | null;
    /**
     * Główny tekst o firmie na stronie /o-nas - historia, wartości, podejście
     */
    description?: string | null;
    /**
     * Zdjęcie obok opisu firmy na stronie /o-nas (np. warsztat, meble)
     */
    image?: (string | null) | Media;
  };
  /**
   * Mały złoty tekst nad nagłówkiem, np. "Nasz zespół"
   */
  teamLabel?: string | null;
  /**
   * Nagłówek nad kartami zespołu na stronie /o-nas
   */
  teamHeading?: string | null;
  /**
   * Tekst pod nagłówkiem sekcji zespołu na stronie /o-nas
   */
  teamDescription?: string | null;
  /**
   * Osoby wyświetlane jako karty na stronie /o-nas
   */
  team?:
    | {
        /**
         * np. "Kamil Kujawski"
         */
        name: string;
        /**
         * Tekst pod imieniem, np. "Stolarz", "Projektant wnętrz"
         */
        role: string;
        /**
         * Opis osoby - doświadczenie, specjalizacja, pasja
         */
        description: string;
        /**
         * Zdjęcie osoby na karcie na stronie /o-nas
         */
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  meta?: {
    /**
     * Tytuł strony /o-nas w wynikach Google i na karcie przeglądarki
     */
    title?: string | null;
    /**
     * Opis pod tytułem w wynikach Google dla strony /o-nas
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        newTab?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  description?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  contactInfo?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  siteUrl?: T;
  logo?: T;
  favicon?: T;
  companyInfo?:
    | T
    | {
        name?: T;
        nip?: T;
        address?: T;
        phone?: T;
        email?: T;
        googleMapsUrl?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  ogImage?: T;
  seo?:
    | T
    | {
        defaultTitle?: T;
        titleTemplate?: T;
        defaultDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
        slides?:
          | T
          | {
              image?: T;
              id?: T;
            };
        ctaText?: T;
        ctaLink?: T;
        secondaryCtaText?: T;
        secondaryCtaLink?: T;
      };
  videoSection?:
    | T
    | {
        label?: T;
        heading?: T;
        videos?:
          | T
          | {
              title?: T;
              url?: T;
              thumbnail?: T;
              id?: T;
            };
      };
  servicesSection?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
      };
  projectsSection?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        ctaText?: T;
        ctaLink?: T;
      };
  ctaBanner?:
    | T
    | {
        heading?: T;
        description?: T;
        backgroundImage?: T;
        ctaText?: T;
        ctaLink?: T;
      };
  testimonialsSection?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
        image?: T;
      };
  intro?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        image?: T;
      };
  teamLabel?: T;
  teamHeading?: T;
  teamDescription?: T;
  team?:
    | T
    | {
        name?: T;
        role?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}